using System;
namespace Rosie
{
	public static class DeviceCapabilityKeys
	{
		public const string Switch = "switch";
		public const string Thermostat = "thermostat";
		public const string AccelerationSensor = "accelerationSensor";
		public const string Actuator = "actuator";
		public const string Alarm = "alarm";
		public const string AudioNotification = "audioNotification";
		public const string Battery = "battery";
		public const string Beacon = "beacon";
		public const string Bridge = "bridge";
		public const string Bulb = "bulb";
		public const string Button = "button";
		public const string CarbonDioxideMeasurement = "carbonDioxideMeasurement";
		public const string CarbonMonoxideDetector = "carbonMonoxideDetector";
		public const string ColorControl = "colorControl";
		public const string ColorTemperature = "colorTemperature";
		public const string Configuration = "configuration";
		public const string Consumable = "consumable";
		public const string ContactSensor = "contactSensor";
		public const string DoorControl = "doorControl";
		public const string DoorState = "doorState";
		public const string EnergyMeter = "energyMeter";
		public const string EstimatedTimeOfArrival = "estimatedTimeOfArrival";
		public const string HoldableButton = "holdableButton";
		public const string IlluminanceMeasurement = "illuminanceMeasurement";
		public const string ImageCapture = "imageCapture";
		public const string Indicator = "indicator";
		public const string InfraredLevel = "infraredLevel";
		public const string Light = "light";
		public const string Lock = "lock";
		public const string LockOnly = "lockOnly";
		public const string MediaController = "mediaController";
		public const string MomentarySwitch = "momentarySwitch";
		public const string MotionSensor = "motionSensor";
		public const string MusicPlayer = "musicPlayer";
		public const string Notification = "notification";
		public const string PhMeasurement = "phMeasurement";
		public const string Polling = "polling";
		public const string PowerMeter = "powerMeter";
		public const string PowerSource = "powerSource";
		public const string PresenceSensor = "presenceSensor";
		public const string Refresh = "refresh";
		public const string RelativeHumidityMeasurement = "relativeHumidityMeasurement";
		public const string Sensor = "sensor";
		public const string ShockSensor = "shockSensor";
		public const string SignalStrength = "signalStrength";
		public const string SleepSensor = "sleepSensor";
		public const string SmokeDetector = "smokeDetector";
		public const string SoundPressureLevel = "soundPressureLevel";
		public const string SoundSensor = "soundSensor";
		public const string SpeechRecognition = "speechRecognition";
		public const string SpeechSynthesis = "speechSynthesis";
		public const string StepSensor = "stepSensor";
		public const string SwitchLevel = "switchLevel";
		public const string TamperAlert = "tamperAlert";
		public const string TemperatureMeasurement = "temperatureMeasurement";
		public const string ThermostatCoolingSetpoint = "thermostatCoolingSetpoint";
		public const string ThermostatFanMode = "thermostatFanMode";
		public const string ThermostatHeatingSetpoint = "thermostatHeatingSetpoint";
		public const string ThermostatMode = "thermostatMode";
		public const string ThermostatOperatingState = "thermostatOperatingState";
		public const string ThermostatSetpoint = "thermostatSetpoint";
		public const string ThreeAxis = "threeAxis";
		public const string TimedSession = "timedSession";
		public const string Tone = "tone";
		public const string TouchSensor = "touchSensor";
		public const string UltravioletIndex = "ultravioletIndex";
		public const string Valve = "valve";
		public const string VoltageMeasurement = "voltageMeasurement";
		public const string WaterSensor = "waterSensor";
		public const string WindowShade = "windowShade";
	}
}
